### PR TITLE
react-native upgrade changes

### PR DESCRIPTION
**Pull request by ivanbogdanov**

### CODE REVIEW

**Comment by wmathurin** [comment]
Could you use 0.30 so it lines up with Mobile SDK 4.3.
Also, could you bring the 4.3 version of react.force.*.js (https://github.com/forcedotcom/SalesforceMobileSDK-Shared/tree/master/libs) into https://github.com/forcedotcomlabs/react.force?

**Comment by ivanbogdanov** [comment]
@wmathurin I'd like to use improved animated Modals that were introduced in 0.34

https://github.com/facebook/react-native/releases

**Comment by ivanbogdanov** [comment]
@wmathurin absolutelly: I will update react.force with a separate PR because it is a stand-alone library

**Comment by ivanbogdanov** [comment]
@wmathurin animated modals with 0.34 or no animated modals with 0.30 ?

**Comment by wmathurin** [comment]
Your call - mobile sdk 4.3 is with 0.30, I don't know if it will work seamlessly with 0.34.

**Comment by ivanbogdanov** [comment]
I'll take a risk for now: if I see any issues: I'll jump back to 0.30. Ok?

**Comment by wmathurin** [comment]
Ok

**Comment by ivanbogdanov** [comment]
Great! I'll merge then. I will make a separate PR for react.force update soon

**Pull request merged**
